import { BrainCircuit, FileText, MessageCircleQuestion } from 'lucide-react';

const features = [
  {
    icon: <FileText className="h-8 w-8 text-primary" />,
    title: 'Comprehensive Study Notes',
    description: 'Get well-structured, easy-to-understand notes on any subject in seconds. Perfect for quick reviews or deep dives.',
  },
  {
    icon: <BrainCircuit className="h-8 w-8 text-accent" />,
    title: 'Interactive Flashcards',
    description: 'Master key terms and concepts with our dynamic flashcard generator. Flip, review, and conquer your material.',
  },
  {
    icon: <MessageCircleQuestion className="h-8 w-8 text-primary" />,
    title: 'Challenging Quizzes',
    description: 'Test your knowledge with multiple-choice quizzes tailored to your study topic. Get instant feedback and improve.',
  },
];

export function Features() {
  return (
    <section id="features" className="py-20 sm:py-32">
      <div className="container mx-auto px-4">
        <div className="mx-auto max-w-2xl lg:text-center">
          <h2 className="text-base font-semibold leading-7 text-primary">Learn Faster</h2>
          <p className="mt-2 text-3xl font-bold tracking-tight text-foreground sm:text-4xl font-headline">
            Everything You Need to Study
          </p>
          <p className="mt-6 text-lg leading-8 text-muted-foreground">
            Our platform provides a complete suite of tools to enhance your learning experience, all generated by powerful AI.
          </p>
        </div>
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.title} className="flex flex-col">
                <dt className="flex items-center gap-x-3 text-base font-semibold leading-7 text-foreground">
                  {feature.icon}
                  {feature.title}
                </dt>
                <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-muted-foreground">
                  <p className="flex-auto">{feature.description}</p>
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>
    </section>
  );
}
