
import { Header } from '@/components/landing/Header';
import { Footer } from '@/components/landing/Footer';

export default function PrivacyPage() {
    const lastUpdated = "August 1, 2024";

    return (
        <div className="flex min-h-screen flex-col bg-background">
            <Header />
            <main className="flex-grow container mx-auto px-4 py-12 md:py-20">
                <div className="prose prose-invert max-w-4xl mx-auto bg-card p-8 md:p-12 rounded-xl border">
                    <h1>Privacy Policy</h1>
                    <p className="text-muted-foreground">Last updated: {lastUpdated}</p>

                    <p>ScholarAI ("us", "we", or "our") operates the [Your Website URL] website (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

                    <h2>1. Information Collection and Use</h2>
                    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

                    <h3>Types of Data Collected</h3>
                    <ul>
                        <li><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to: Email address, First name and last name, Cookies and Usage Data.</li>
                        <li><strong>Usage Data:</strong> We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</li>
                        <li><strong>User-Generated Content:</strong> We collect the topics you input and the content generated by our AI models on your behalf (notes, flashcards, quizzes). This data is stored to provide you with access to your study materials.</li>
                    </ul>

                    <h2>2. Use of Data</h2>
                    <p>ScholarAI uses the collected data for various purposes:</p>
                    <ul>
                        <li>To provide and maintain the Service</li>
                        <li>To notify you about changes to our Service</li>
                        <li>To provide customer care and support</li>
                        <li>To provide analysis or valuable information so that we can improve the Service</li>
                        <li>To monitor the usage of the Service</li>
                        <li>To detect, prevent and address technical issues</li>
                    </ul>

                    <h2>3. Data Sharing and Disclosure</h2>
                    <p>We do not sell your personal data. We may share your data with third-party service providers to facilitate our Service, such as:</p>
                    <ul>
                        <li><strong>Firebase (Google):</strong> We use Firebase for user authentication and hosting. Their privacy policy can be viewed at <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.</li>
                        <li><strong>Google AI (Gemini):</strong> Your input topics are sent to Google's AI models to generate study materials. We do not allow Google to use your data to train their models.</li>
                    </ul>

                    <h2>4. Data Storage and Security</h2>
                    <p>Your study materials (notes, flashcards, etc.) are stored in your browser's local storage and are namespaced to your user account. The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>

                    <h2>5. Your Data Rights</h2>
                    <p>You have the right to access, update or delete the information we have on you. You can manage your account and associated data from your profile page or by contacting us directly.</p>

                    <h2>6. Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, please contact us at: hello@scholarai.app</p>
                </div>
            </main>
            <Footer />
        </div>
    );
}
